baseURL = "https://julia.school/"
languageCode = "en-au"
title = "Julia School"
theme = "moonbooth-seo-theme"
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']
[params]
	blogFooterLinkText = "Julia Tutorials"
    blogSection = "julia"
	color = "#8CF67B"
	dateMarkedUpdated = true
	description = "Here's how I've used Julia in my SEO role at a big Australian tech company."
	rssTitle = "Julia Tutorials | julia.school"
	seoTitle = "Julia tutorials for web scraping and dataframe pivots"
[markup]
	[markup.goldmark.renderer]
		unsafe = true
	[markup.tableOfContents]
		endLevel = 2
		ordered = false
		startLevel = 2
	[markup.highlight]
		tabWidth = 2
[minify]
	disableSVG = true
