[context.production.environment]
	HUGO_VERSION = "0.80.0"

[build]
	publish = "public"
	command = "hugo --minify --buildFuture"

[[redirects]]
	from = "/index.xml"
	to = "/julia/index.xml/"
	status = 301

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404

[[headers]]
  for = "/*"
  [headers.values]
	Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
